// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqavwwqebcsshsdrvczz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYXZ3d3FlYmNzc2hzZHJ2Y3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTY5ODksImV4cCI6MjA4OTA3Mjk4OX0.voZh3tRgJs1d45LbBmjU6JtgqRCpn4ZLcqQqCns0h8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});