const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    // Get leads from the past 7 days
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    const since = sevenDaysAgo.toISOString();

    const leadsRes = await fetch(
      `${supabaseUrl}/rest/v1/leads?created_at=gte.${since}&order=created_at.desc`,
      {
        headers: {
          'apikey': serviceRoleKey,
          'Authorization': `Bearer ${serviceRoleKey}`,
        },
      }
    );
    const leads = await leadsRes.json();

    // Get notification email
    const configRes = await fetch(
      `${supabaseUrl}/rest/v1/site_config?key=eq.notification_email&select=value`,
      {
        headers: {
          'apikey': serviceRoleKey,
          'Authorization': `Bearer ${serviceRoleKey}`,
        },
      }
    );
    const configData = await configRes.json();
    const notifyEmail = configData?.[0]?.value?.email || 'info@dangpestcontrol.com';

    // Build summary
    const totalLeads = leads.length;
    const newLeads = leads.filter((l: { status: string }) => l.status === 'new').length;
    const contactedLeads = leads.filter((l: { status: string }) => l.status === 'contacted').length;
    const closedLeads = leads.filter((l: { status: string }) => l.status === 'closed').length;

    // Service breakdown
    const serviceCounts: Record<string, number> = {};
    for (const lead of leads) {
      const svc = lead.service || 'Unspecified';
      serviceCounts[svc] = (serviceCounts[svc] || 0) + 1;
    }

    const serviceBreakdown = Object.entries(serviceCounts)
      .sort((a, b) => b[1] - a[1])
      .map(([service, count]) => `  • ${service}: ${count}`)
      .join('\n');

    const weekOf = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

    const report = `
Weekly Lead Summary — ${weekOf}
================================

📊 Overview (Last 7 Days)
  Total Leads: ${totalLeads}
  New (Awaiting Response): ${newLeads}
  Contacted: ${contactedLeads}
  Closed: ${closedLeads}

🐛 Leads by Service
${serviceBreakdown || '  No leads this week.'}

📋 Recent Leads
${leads.slice(0, 10).map((l: { name: string; service: string; phone: string; email: string; created_at: string }) =>
  `  • ${l.name} — ${l.service || 'General'} — ${l.phone || l.email || 'No contact'} — ${new Date(l.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`
).join('\n') || '  None'}

---
This report was automatically generated by your Dang Pest Control dashboard.
    `.trim();

    // Log the report (email integration placeholder)
    console.log(`📧 Weekly report for ${notifyEmail}:`);
    console.log(report);

    return new Response(JSON.stringify({
      success: true,
      recipient: notifyEmail,
      summary: {
        total: totalLeads,
        new: newLeads,
        contacted: contactedLeads,
        closed: closedLeads,
        topServices: Object.entries(serviceCounts).sort((a, b) => b[1] - a[1]).slice(0, 5),
      },
      report,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Error generating weekly report:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
